apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.roleBinding.name }}
  namespace: {{ .Values.roleBinding.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  kind: {{ .Values.roleBinding.roleRef.kind }}
  name: {{ .Values.roleBinding.roleRef.name }}
  apiGroup: {{ .Values.roleBinding.roleRef.apiGroup }}

