apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Values.role.namespace }}
rules:
  - apiGroups: {{ .Values.role.rules[0].apiGroups }}
    resources: {{ .Values.role.rules[0].resources }}
    verbs: {{ .Values.role.rules[0].verbs }}

